URLTS: 'http://127.0.0.0:8090'  # TorrServer URL
TSUser: ''  # TorrServer username
TSPass: ''  # TorrServer password
URLJAC: 'https://example.com'  # Jackett URL
APIKEY: ''  # Api key for jackett
PLAYER: '/bin/mpv'  # Path to media-player
fzf: FzfPrompt('/bin/fzf')  # Path to FZF
